# Generated by Django 5.2.9 on 2025-12-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Например: 'Введение в Python'", max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Детальное описание урока', verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Время начала урока')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания урока')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='lesson_less_status_faff9e_idx'), models.Index(fields=['start_time'], name='lesson_less_start_t_2f4cd9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='lesson_end_after_start')],
            },
        ),
    ]
